version: "3.8"

services:
  app:
    build: .
    container_name: dev-learn-api
    ports:
      - "3002:80"
    env_file:
      - .env.production
    volumes:
      - .:/var/www/html

    depends_on:
      db:
        condition: service_healthy

    command: ["apache2-foreground"]

  db:
    image: postgres:16
    container_name: dev-learn-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: